### PR TITLE
Updated Clumsy Bird to melonJS version 2.1.1

### LINKED ISSUE #63: Update to melonJS 2.1

### PR DESCRIPTION
**Pull request by jdrorrer**
Fixes #63. Changes include...

- added latest minified version of melonJS (2.1.1)
- added latest debugPanel.js
- updated instances of spritewidth/spriteheight to framewidth/frameheight
- updated me.video.init to match new pattern
- updated instances of me.Sprite and me.ImageLayer to match up with new properties pattern (x, y, settings)
- anywhere where me.Font references context, updated it to use renderer instead
- in 2.1.1 `this.updateBounds();` is deprecated. Replaced all instances with `me.Rect.prototype.updateBounds.apply(this);`
- in 2.1.1 entities have a me.Rect added with the entity's settings.width and settings.height by default, so removed instances where me.Rect shape was being added with default width/height, and also removed default me.Rect shapes and added new me.Rect shapes where width/height were not set to defaults

### CODE REVIEW

**Comment by ellisonleao** [comment]
Hey @jdrorrer thanks for the PR, i will take a look and return on this soon!

**Comment by jdrorrer** [comment]
@ellisonleao Awesome, glad to help!  One other issue I found is the Facebook SDK doesn't work properly with melonJS. I put in a pull request to melonJS to patch this issue as well: https://github.com/melonjs/melonJS/pull/702

**Comment by ellisonleao** [comment]
I will handle the FB issue later. Thanks for the PR!

**Comment by jdrorrer** [comment]
Sounds good to me... You're welcome @ellisonleao!

**Pull request merged**
